# Generated by Django 3.2.3 on 2021-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_ticker',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
