# Generated by Django 3.2.3 on 2021-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_posts', '0002_post_related_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_ticker',
            field=models.CharField(default='', max_length=10),
        ),
    ]
